### ISSUE TITLE
Gstreamer Plugins Requirements

### ISSUE THREAD

**Issue by FranGoitia** [hslbck/gnome-shell-extension-radio#112]
What gstreamer plugins does it need ? I'm on OpenSuse 42.3 and installed all the gstreamer plugins available but when trying to start a radio it keeps saying misssing plugin

**Comment by hslbck** [comment]
Hi,

depends which format your stream is using. For mp3 install `gstreamer1.0-plugins-ugly`, see related issue https://github.com/hslbck/gnome-shell-extension-radio/issues/64#issuecomment-299622858. If this alone doesn't help try restarting your machine in order to get those plugins loaded properly.
