### ISSUE TITLE
requires gir1.2-gst-plugins-base-1.0 on PopOS 20.04, shell extension 3.36.8

### ISSUE THREAD

**Issue by j2l** [hslbck/gnome-shell-extension-radio#170]
Hello,
Second computer, second issue installing your great extension.
Fixed the same way, install gir1.2-gst-plugins-base-1.0

Before it was an issue with 3.36, so I guess it's an issue with PopOS.

**Comment by riker09** [comment]
I had trouble getting this extension running on Pop!_OS 21.04, this issue has given me the solution:

```bash
sudo apt install gir1.2-gst-plugins-base-1.0
```

Thanks, @j2l 

Can you maybe add this as a hint to the Readme? Can this package be listed as a dependency so that it is installed automatically on Pop!_OS when enabling this extension? Sorry, I'm very new to Gnome 40 and Pop!_OS. I've been using Elementary OS for the past few years (which is missing a decent internet radio tray application like this, btw.)

**Comment by j2l** [comment]
HI @riker09 
I just let the owner know about it :smiley_cat:
