### ISSUE TITLE
Multimedia Keys not work in Gnome 3.24

### ISSUE THREAD

**Issue by stmc** [hslbck/gnome-shell-extension-radio#63]
Multimedia Keys not work in Gnome 3.24

ArchLinux x64
Gnome 3.24

**Comment by hslbck** [comment]
Hi stmc,

seems to be same issue as https://github.com/hslbck/gnome-shell-extension-radio/issues/33

Media keys are not working on Archlinux with Wayland after a logout. On X they should work fine.
Disabling and enabling the media key setting only solves the issue temporarily.

I'll check further, but currently I have got no idea what's the issue here.
