### ISSUE TITLE
seperate volume control for extension

### ISSUE THREAD

**Issue by HeikoAdams** [hslbck/gnome-shell-extension-radio#8]
The extension uses the volume level from gnome-shell but it would be nice if there would be a seperate volume control like rhythmbox or others.

**Comment by hslbck** [comment]
I thought about an explicit volume control, too. But my point of view is, that this extension "extends" the functionality of the gnome shell which has already a volume control nearby. So I don't see the necessity for a separate volume control compared to standalone applications like rhythmbox etc. But if you want it, you can fork the extension and maybe reuse the volume control code parts in the extension.

**Comment by HeikoAdams** [comment]
What about: the following scenario: GS volume is at 100% and all other app have volume levels <= 100%. If I now want the webradio to be subdued (ie. 25%) that would raise down all other app volumes and some app might be muted due to that.

**Comment by hslbck** [comment]
ok I'll get your use case. But this means the audio has to be decoupled from gnome-shell and treated like any other application. This means on the other hand that the extensions doesn't fit for that use case.
I'll have a look into it, if it is not to much effort to change it, I'll implement it, otherwise it'll stay in its current state.

**Comment by HeikoAdams** [comment]
Sounds like a good deal ;-)
